url: "https://tombrandis.uk" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Tom Brandis" # the name of your site, e.g. ACME Corp.
permalink: none
exclude: [deploy]

collections:
  posts:
    output: true
    permalink: /:collection/:title.html
  reports:
    output: true
  presentations:
    output: true

compress_html:
  blanklines: true