url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
permalink: none
exclude: [deploy]

collections:
  posts:
    output: true
    permalink: /:collection/:title.html
  
sass:
  style: compressed